US040 - Login System (Overhaul)
BlankAmber/Kainos-RRAS-API pull request #18
Opened 2023-12-15 14:45 UTC by BlankAmber

# Pull Request Checklist

Please follow all these rules before merging your branch.
- [ ] Must reference a ticket
- [ ] Must implement tests where appropirate
- [ ] Must have useful documentation
- [ ] Must adhere to the naming conventions
- [ ] Must not commit confidential information 

Once all requirements above are fulfilled, your pull request has no merge conflicts, and you have two approvals from the approved approvers, then it can be tested and signed off.

Relevant tickets:
- [US040 - Login System](https://tasks.office.com/kainos.com/Home/Task/b_OhVXRyQEGETWG0--tRX5YAKUk2?Type=TaskLink&Channel=Link&CreatedTime=638382480756900000)
- [US041 - Authorisation System](https://tasks.office.com/kainos.com/Home/Task/1tQcqEQ2KkWmi3YhtxdI2JYAOcgr?Type=TaskLink&Channel=Link&CreatedTime=638382480898780000)

Changes:
- Replaced SHA-256 with Argon2 using [password4j](https://github.com/Password4j/password4j)
  - To generate the hashed passwords (should be implemented in [US024 - Registration System](https://tasks.office.com/kainos.com/Home/Task/-LpElUzK40epI97zNycNUZYABeGF?Type=TaskLink&Channel=Link&CreatedTime=638382482281550000)) use: `Password.hash(login.getPassword()).addRandomSalt(12).withArgon2()`

TODO:
- Use JWT instead of a randomly generated UUID
- Authorisation

Screenshots:
Login still works after the hashing algorithm change :)
<img width="399" alt="Screenshot 2023-12-15 at 14 44 25" src="https://github.com/BlankAmber/Kainos-RRAS-API/assets/145449058/91ac4add-f6fd-4063-91df-2437c6adf2fc">

2023-12-18 09:12 UTC, adammarshall745 submitted a review, later dismissed
Looks good! Tests run beautifully (:

2023-12-18 15:19 UTC, jkelso662 requested changes
Really good! Great overhaul and very close to how we might implement this on project. Code also looks a lot cleaner using these other libraries! Left one comment for a class that needs fixing. Also seeing a few empty constructors. Make sure you ask the question, does it make sense here to create an empty object? 

One other thing to think about - looks like you intend on sending the JWT token in the URL as a query parameter. It is one way of doing it but might be more common to have it in the request body or more common than that - in an Auth header. I assume you'll store your token in your front end session object? Anyway - really good work. Yous a re flying through this!

2023-12-18 15:19 UTC, jkelso662 commented on src/main/java/org/kainos/ea/db/RoleID.java
> +}
Nearly! I think what you need an ENUM class :)

2023-12-19 14:26 UTC, adammarshall745 approved these changes
Good improvements Samuel b. I have re run the tests and they passed fine

2023-12-19 14:41 UTC, jkelso662 approved these changes
Amazing! 🥇

2023-12-19 14:42 UTC, merged