B002 - Create Database script
BlankAmber/Kainos-RRAS-API pull request #2
Opened 2023-12-01 09:41 UTC by adammarshall745

This script is to create the database.

2023-12-01 09:49 UTC, BlankAmber approved these changes
FANTASTIC SCRIPT!

2023-12-01 09:49 UTC, BlankAmber commented
The permissions script needs to be made, I am unable to test this. Please do not commit the permissions script

2023-12-05 14:53 UTC, jkelso662 requested changes
There's a lot in here that is not to do with your schema script, and also stuff that I think is already in your branch sign-off branch. Worth pulling the latest changes to make sure. Checkout a couple of other comments.

2023-12-05 14:53 UTC, jkelso662 commented on database/DatabaseScript.sql
Will this script not fail if the schema is already created?

2023-12-05 14:53 UTC, lullabelle commented
Where is the rest of the database script? There are only 2 lines in here. This needs to be executable should the database need recreated.
Gitignore and other bits and pieces in here not related to ticket

2023-12-05 14:57 UTC, BlankAmber commented on database/DatabaseScript.sql
Fixed in [#bb90436 ](https://github.com/BlankAmber/Kainos-RRAS-API/pull/2/commits/bb90436e4942bdfbbf1f7439a218bff3f602c78f)

2023-12-05 15:00 UTC, BlankAmber commented
> There's a lot in here that is not to do with your schema script, and also stuff that I think is already in your branch sign-off branch.
> Gitignore and other bits and pieces in here not related to ticket
This should be fixed now

2023-12-05 15:02 UTC, BlankAmber commented
> Where is the rest of the database script? There are only 2 lines in here.

We were planning on adding the tables incrementally as we do the tickets. E.g. US001 would add the `job_roles` table, ES040 would add the `users`, `tokens`, and `roles` tables. Would that be okay, or should we add more tables to start with?

2023-12-06 09:38 UTC, jkelso662 approved these changes

2023-12-06 09:39 UTC, merged